chz added

diff --git a/sh/rmate b/sh/rmate
--- a/sh/rmate
+++ b/sh/rmate
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 # rmate
-# Copyright (C) 2011-2015 by Harald Lapp <harald@octris.org>
+# Copyright (C) 2011-2017 by Harald Lapp <harald@octris.org>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -33,8 +33,8 @@
 
 # init
 #
-version="0.9.5"
-version_date="2015-05-24"
+version="1.0.0"
+version_date="2017-06-29"
 version_string="rmate-sh $version ($version_date)"
 
 # determine hostname
@@ -57,6 +57,7 @@ hostname=$($(hostname_command))
 # default configuration
 host=localhost
 port=52698
+eval home=$(builtin printf "~%q" "${SUDO_USER:-$LOGNAME}")
 
 function load_config {
     local rc_file=$1
@@ -66,7 +67,7 @@ function load_config {
     local port_pattern="^port(:[[:space:]]+|=)([0-9]+)"
 
     if [ -f "$rc_file" ]; then
-        while read row; do
+        while read -r row; do
             if [[ "$row" =~ $host_pattern ]]; then
                 host=${BASH_REMATCH[2]}
             elif [[ "$row" =~ $port_pattern ]]; then
@@ -76,22 +77,19 @@ function load_config {
     fi
 }
 
-for i in "/etc/${0##*/}" ~/."${0##*/}/${0##*/}.rc" ~/."${0##*/}.rc"; do
+for i in "/etc/${0##*/}" $home/."${0##*/}/${0##*/}.rc" $home/."${0##*/}.rc"; do
     load_config $i
 done
 
 host="${RMATE_HOST:-$host}"
 port="${RMATE_PORT:-$port}"
 
-if [[ "$host" = "auto" && "$SSH_CONNECTION" != "" ]]; then
-    host=${SSH_CONNECTION%% *}
-fi
 
 # misc initialization
-filepath=""
-selection=""
-displayname=""
-filetype=""
+filepaths=()
+displaynames=()
+selections=()
+filetypes=()
 verbose=false
 nowait=true
 force=false
@@ -99,7 +97,7 @@ force=false
 # process command-line parameters
 #
 function showusage {
-    echo "usage: $(basename $0) [arguments] file-path  edit specified file
+    echo "usage: $(basename $0) [arguments] [--] file-path  edit specified file
    or: $(basename $0) [arguments] -          read text from stdin
 
 -H, --host HOST  Connect to HOST. Use 'auto' to detect the host from
@@ -107,6 +105,7 @@ function showusage {
 -p, --port PORT  Port number to use for connection. Defaults to $port.
 -w, --[no-]wait  Wait for file to be closed by TextMate.
 -l, --line LINE  Place caret on line number after loading file.
++N               Alias for --line, if N is a number (eg.: +5).
 -m, --name NAME  The display name shown in TextMate.
 -t, --type TYPE  Treat file as having specified type.
 -n, --new        Open in a new window (Sublime Text).
@@ -124,14 +123,19 @@ function log {
 }
 
 function dirpath {
-    (cd `dirname $1` >/dev/null 2>/dev/null; pwd -P)
+    (cd "`dirname "$1"`" >/dev/null 2>/dev/null || { echo "unable to cd to $1 directory" 1>&2; exit; } ; pwd -P)
 }
 
 function canonicalize {
     filepath="$1"
+
+    if [[ "${filepath:0:1}" = "-" ]]; then
+        filepath="./$filepath"
+    fi
+
     dir=`dirpath "$filepath"`
     if [ -L "$filepath" ]; then
-        relativepath=`cd "$dir"; readlink \`basename "$filepath"\``
+        relativepath=`cd "$dir" || { echo "unable to cd to $dir" 1>&2; exit; } ; readlink "\`basename "$filepath"\`"`
         result=`dirpath "$relativepath"`/`basename "$relativepath"`
     else
         result=`basename "$filepath"`
@@ -141,12 +145,16 @@ function canonicalize {
             result="$dir/$result"
         fi
     fi
-    echo $result
+    echo "$result"
 }
 
-while test "${1:0:1}" = "-"; do
+while [[ "${1:0:1}" = "-" || "$1" =~ ^\+([0-9]+)$ ]]; do
     case $1 in
         -)
+            break
+            ;;
+        --)
+            shift
             break
             ;;
         -H|--host)
@@ -164,15 +172,15 @@ while test "${1:0:1}" = "-"; do
             nowait=true
             ;;
         -l|--line)
-            selection=$2
+            selections+=($2)
             shift
             ;;
         -m|--name)
-            displayname=$2
+            displaynames+=($2)
             shift
             ;;
         -t|--type)
-            filetype=$2
+            filetypes+=($2)
             shift
             ;;
         -n|--new)
@@ -185,12 +193,15 @@ while test "${1:0:1}" = "-"; do
             verbose=true
             ;;
         --version)
-            echo $version_string
+            echo "$version_string"
             exit 1
             ;;
         -h|-\?|--help)
             showusage
             exit 1
+            ;;
+        +[0-9]*)
+            selection=${1:1}
             ;;
         *)
             showusage
@@ -201,11 +212,15 @@ while test "${1:0:1}" = "-"; do
     shift
 done
 
-filepath="$1"
+if [[ "$host" = "auto" && "$SSH_CONNECTION" != "" ]]; then
+    host=${SSH_CONNECTION%% *}
+fi
 
-if [ "$filepath" = "" ]; then
+filepaths=("$@")
+
+if [ "${filepaths[*]}" = "" ]; then
     if [[ $nowait = false ]]; then
-        filepath='-'
+        filepaths=('-')
     else
         case "$-" in
             *i*)
@@ -213,45 +228,93 @@ if [ "$filepath" = "" ]; then
                 exit 1
                 ;;
             *)
-                filepath='-'
+                filepaths=('-')
                 ;;
         esac
     fi
 fi
 
-shift
-if [ ! "${#@}" -eq 0 ]; then
-    echo "There is more than one file specified. Opening only $filepath and ignoring other."
-fi
-
-if [ "$filepath" != "-" ]; then
-    realpath=`canonicalize "$filepath"`
-    log $realpath
-
-    if [ -d "$filepath" ]; then
-        echo "$filepath is a directory and rmate is unable to handle directories."
-        exit 1
-    fi
-
-    if [ -f "$realpath" ] && [ ! -w "$realpath" ]; then
-        if [[ $force = false ]]; then
-            echo "File $filepath is not writable! Use -f to open anyway."
-            exit 1
-        elif [[ $verbose = true ]]; then
-            log "File $filepath is not writable! Opening anyway."
-        fi
-    fi
-
-    if [ "$displayname" = "" ]; then
-        displayname="$hostname:$filepath"
-    fi
-else
-    displayname="$hostname:untitled"
-fi
 
 #------------------------------------------------------------
 # main
 #------------------------------------------------------------
+
+function open_file {
+
+    index="$1"
+    filepath="${filepaths[$index]}"
+    selection="${selections[$index]}"
+    filetype="${filetypes[$index]}"
+    displayname="${displaynames[$index]}"
+
+    if [ "$filepath" != "-" ]; then
+        realpath=`canonicalize "$filepath"`
+        log "$realpath"
+
+        if [ -d "$filepath" ]; then
+            echo "$filepath is a directory and rmate is unable to handle directories."
+            exit 1
+        fi
+
+        if [ -f "$realpath" ] && [ ! -w "$realpath" ]; then
+            if [[ $force = false ]]; then
+                echo "File $filepath is not writable! Use -f to open anyway."
+                exit 1
+            elif [[ $verbose = true ]]; then
+                log "File $filepath is not writable! Opening anyway."
+            fi
+        fi
+
+        if [ "$displayname" = "" ]; then
+            displayname="$hostname:$filepath"
+        fi
+    else
+        displayname="$hostname:untitled"
+    fi
+
+    echo "open" 1>&3
+    echo "display-name: $displayname" 1>&3
+    echo "real-path: $realpath" 1>&3
+    echo "data-on-save: yes" 1>&3
+    echo "re-activate: yes" 1>&3
+    echo "token: $filepath" 1>&3
+
+    if [[ $new = true ]]; then
+        echo "new: yes"  1>&3
+    fi
+
+    if [ "$selection" != "" ]; then
+        echo "selection: $selection" 1>&3
+    fi
+
+    if [ "$filetype" != "" ]; then
+        echo "file-type: $filetype" 1>&3
+    fi
+
+    if [ "$filepath" != "-" ] && [ -f "$filepath" ]; then
+        filesize=`ls -lLn "$realpath" | awk '{print $5}'`
+        echo "data: $filesize" 1>&3
+        cat "$realpath" 1>&3
+    elif [ "$filepath" = "-" ]; then
+        if [ -t 0 ]; then
+            echo "Reading from stdin, press ^D to stop"
+        else
+            log "Reading from stdin"
+        fi
+
+        # preserve trailing newlines
+        data=`cat; echo x`
+        data=${data%x}
+        filesize=$(echo -ne "$data" | wc -c)
+        echo "data: $filesize" 1>&3
+        echo -n "$data" 1>&3
+    else
+        echo "data: 0" 1>&3
+    fi
+
+    echo 1>&3
+}
+
 function handle_connection {
     local cmd
     local name
@@ -259,7 +322,7 @@ function handle_connection {
     local token
     local tmp
 
-    while read 0<&3; do
+    while read -r 0<&3; do
         REPLY="${REPLY#"${REPLY%%[![:space:]]*}"}"
         REPLY="${REPLY%"${REPLY##*[![:space:]]}"}"
 
@@ -268,7 +331,7 @@ function handle_connection {
         token=""
         tmp=""
 
-        while read 0<&3; do
+        while read -r 0<&3; do
             REPLY="${REPLY#"${REPLY%%[![:space:]]*}"}"
             REPLY="${REPLY%"${REPLY##*[![:space:]]}"}"
 
@@ -318,56 +381,21 @@ function handle_connection {
 
 # connect to textmate and send command
 #
-exec 3<> /dev/tcp/$host/$port
+exec 3<> "/dev/tcp/$host/$port"
 
 if [ $? -gt 0 ]; then
     echo "Unable to connect to TextMate on $host:$port"
     exit 1
 fi
 
-read server_info 0<&3
+read -r server_info 0<&3
 
 log $server_info
 
-echo "open" 1>&3
-echo "display-name: $displayname" 1>&3
-echo "real-path: $realpath" 1>&3
-echo "data-on-save: yes" 1>&3
-echo "re-activate: yes" 1>&3
-echo "token: $filepath" 1>&3
+for i in "${!filepaths[@]}"; do
+    open_file "$i"
+done
 
-if [[ $new = true ]]; then
-    echo "new: yes"  1>&3
-fi
-
-if [ "$selection" != "" ]; then
-    echo "selection: $selection" 1>&3
-fi
-
-if [ "$filetype" != "" ]; then
-    echo "file-type: $filetype" 1>&3
-fi
-
-if [ "$filepath" != "-" ] && [ -f "$filepath" ]; then
-    filesize=`ls -lLn "$realpath" | awk '{print $5}'`
-    echo "data: $filesize" 1>&3
-    cat "$realpath" 1>&3
-elif [ "$filepath" = "-" ]; then
-    if [ -t 0 ]; then
-        echo "Reading from stdin, press ^D to stop"
-    else
-        log "Reading from stdin"
-    fi
-
-    data=$(cat)
-    filesize=$(echo -e "$data" | wc -c)
-    echo "data: $filesize" 1>&3
-    echo "$data" 1>&3
-else
-    echo "data: 0" 1>&3
-fi
-
-echo 1>&3
 echo "." 1>&3
 
 if [[ $nowait = true ]]; then
